spring.application.name=universidad

server.port=8086

# MySQL 
app.mysql.url=jdbc:mysql://localhost:3306/universidad_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
app.mysql.username=root
app.mysql.password=root
app.mysql.driver=com.mysql.cj.jdbc.Driver

# PostgreSQL
app.postgres.url=jdbc:postgresql://localhost:5432/universidad_db
app.postgres.username=postgres
app.postgres.password=root
app.postgres.driver=org.postgresql.Driver

# MariaDB
app.mariadb.url=jdbc:mysql://localhost:3307/universidad_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
app.mariadb.username=root
app.mariadb.password=root
app.mariadb.driver=com.mysql.cj.jdbc.Driver
